IEP-Project-Web/Controllers/AuctionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IEP_Project_Web.Models;
using Microsoft.AspNet.Identity;

namespace IEP_Project_Web.Controllers
{
    public class AuctionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult WonAuctions()
        {

            using (var dbContext = ApplicationDbContext.Create())
            {
                var currentUser = User.Identity.GetUserId();
                var auctionsListQuery = from aw in dbContext.AuctionWinners
                                        join a in dbContext.Auctions on aw.Auction.AuctionId equals a.AuctionId
                                        where aw.Winner.Id == currentUser
                                        select a;
                ViewBag.AuctionsList = auctionsListQuery.ToList();
            }
            return View();
        }

        // GET: Auctions
        public ActionResult Index()
        {
            return View(db.Auctions.ToList());
        }

        // GET: Auctions/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            return View(auction);
        }

        // GET: Auctions/Create
        public ActionResult Create()
        {
            AuctionCreateViewModel auction = new AuctionCreateViewModel
            {
                Duration = 5 // default duration here
            };

            return View(auction);
        }

        // POST: Auctions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        // CurrentPrice,CreatedAt,OpenedAt,ClosedAt,Status
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Image,Duration,StartingPrice")] AuctionCreateViewModel auctionViewModel)
        {
            if (ModelState.IsValid)
            {
                Auction auction = new Auction
                {
                    AuctionId = Guid.NewGuid(),
                    Name = auctionViewModel.Name,
                    Duration = auctionViewModel.Duration,
                    StartingPrice = auctionViewModel.StartingPrice,
                    CurrentPrice = auctionViewModel.StartingPrice,
                    CreatedAt = DateTime.UtcNow,
                    Status = "READY"
                };

                // Check if the file is an image -- if it is, persist it.

                var uploadedFile = auctionViewModel.Image;
                var uploadedFileBytes = new byte[uploadedFile.ContentLength];
                uploadedFile.InputStream.Read(uploadedFileBytes, 0, uploadedFileBytes.Length);

                bool isImageFile;   

                try
                {
                    Image.FromStream(new System.IO.MemoryStream(uploadedFileBytes)).Dispose();
                    isImageFile = true;
                }
                catch (OutOfMemoryException)
                {
                    isImageFile = false;
                }

                // If the file is not an image, return with an error.
                if (!isImageFile)
                {
                    ModelState.AddModelError("ImageToUpload", "The file has to be an image!");
                    return View(auctionViewModel);
                }

                // Otherwise remember the image.
                auction.Image = uploadedFileBytes;

                db.Auctions.Add(auction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(auctionViewModel);
        }

        // GET: Auctions/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // POST: Auctions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuctionId,Name,Image,Duration,StartingPrice,CurrentPrice,CreatedAt,OpenedAt,ClosedAt,Status")] Auction auction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(auction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(auction);
        }

        // GET: Auctions/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // POST: Auctions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Auction auction = db.Auctions.Find(id);
            db.Auctions.Remove(auction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IEP-Project-Web/Views/Auctions/Create.cshtml
@model IEP_Project_Web.Models.AuctionCreateViewModel

@{
    ViewBag.Title = "New Auction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Auctions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBoxFor(model => model.Image, new { type = "file" } )*@
                @Html.TextBoxFor(model => model.Image, htmlAttributes: new {  @type = "file", @accept = ".png, .jpg, .jpeg"})   
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IEP-Project-Web/Views/Auctions/Delete.cshtml
@model IEP_Project_Web.Models.Auction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Auction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClosedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClosedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IEP-Project-Web/Views/Auctions/Details.cshtml
@model IEP_Project_Web.Models.Auction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Auction - @Model.Name</h4>
    <hr />

    <div class="row" style="margin-top: 50px">
        <div class="col-md-offset-3 col-md-6">
            <div class="card">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" style="width: 100%" />
                <div class="container" style="text-align:center">

                    <h3 style="color: cadetblue"> @Model.Name </h3>
                    <hr />
                    <h4> 00:00:10 </h4>
                    <h4 style="color: forestgreen"> $ @Model.CurrentPrice </h4>
                    <h5> <i> User </i> </h5>

                    <!-- videti sta ako je korisnik poslednji koji je bidovao -->
                    @if (Model.Status == "OPENED")
                    {
                        @:<button class="bid-now-button-image" onclick="Auctions/BidOn/@Model.AuctionId?currentUserTODO"></button>
                    }
                    else
                    {
                        @: <button class="sold-out-button-image" disabled></button>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="margin-top: 50px">
        <div class="col-md-offset-2 col-md-8">
            <table class="table" style="width: 100%;">
                <tr>
                    <th>
                        User
                    </th>
                    <th>
                        Tokens
                    </th>
                    <th>
                        Created At
                    </th>
                </tr>
                @{ 
                    if (Model.Bids != null)
                    {
                        foreach (var bid in Model.Bids)
                        {
                        <tr>
                            <td>
                                <i> @bid.User.Name &nbsp; @bid.User.Surname (@bid.User.Email)</i>
                            </td>
                            <td>
                                @bid.Tokens
                            </td>
                            <td>
                                @bid.CreatedAt
                            </td>
                        </tr>
                            }
                        }
                    }
            </table>
            
            </div>
    </div>

</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AuctionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

IEP-Project-Web/Views/Auctions/Edit.cshtml
@model IEP_Project_Web.Models.Auction

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Auction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AuctionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpenedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClosedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClosedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClosedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IEP-Project-Web/Views/Auctions/Index.cshtml
@model IEnumerable<IEP_Project_Web.Models.Auction>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartingPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpenedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClosedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartingPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpenedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClosedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AuctionId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AuctionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AuctionId })
        </td>
    </tr>
}

</table>

IEP-Project-Web/Views/Auctions/WonAuctions.cshtml
@{
    ViewBag.Title = "WonAuctions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Won Auctions</h2>

@{
    var auctionCount = ViewBag.AuctionsList.Count;
    int i = 0;
    foreach (var auction in ViewBag.AuctionsList)
    {
        if (i == 0)
        {
            @:<div class="row" style="margin-top: 50px">
            }
            <div class="col-md-3">
                <div class="card">
                    <img src="data:image;base64,@System.Convert.ToBase64String(auction.Image)" style="width: 100%" />
                    <div class="container" style="text-align:center">

                        <h3> <a href="Auctions/Details/@auction.AuctionId" style="color: cadetblue"> @auction.Name </a></h3>
                        <hr />
                        <h4> 00:00:10 </h4>
                        <h4 style="color: forestgreen"> $ @auction.CurrentPrice </h4>
                        <h5> <i> User </i> </h5>
                        <button class="sold-out-button-image" disabled></button>
                        
                    </div>
                </div>
            </div>
            if (i == 3)
            {
                @: </div>
            i = 0;
        }
        else
        {
            i++;
            if (i == auctionCount)
            {
                @: </div>
            }
        }
    }
}